### PR TITLE
zephyr: Allow to specify extra arguments to imgtool

### PR DESCRIPTION
**Pull request by kurddt**
The same is possible for zephyr application

Signed-off-by: Guillaume Lager <g.lager@innoseis.com>

### CODE REVIEW

**Comment by kurddt** [comment]
The keystore I use is password protected and I need a non-interactive way to retrieve it.

**Comment by kurddt** [comment]
The getpub command get the public part of a key pair. The keystore containing both public and private part I like it to be password protected.

**Comment by utzig** [comment]
> The getpub command get the public part of a key pair. The keystore containing both public and private part I like it to be password protected.

`getpub` also accepts the public key, so you can just extract the public key part from the keypair, but I understand your issue now.

**Comment by kurddt** [comment]
@nvlsianpu This PR is quite old but any chance to have it merged if I rebase ? else I will close the PR

**Comment by nvlsianpu** [comment]
@kurddt
> This PR is quite old but any chance to have it merged if I rebase ? else I will close the PR

I think It might go (...but not here),
Your patch should be redirected o the mcu-tool/mcuboot - It will be inherited by this fork once another synchronization.
This MCUboot fork is mainly for providing MCUboot as zephyr module. We want to keep empty code diff on synchronization points.

**Pull request closed without merging**
