### PR TITLE
synchronization 08122021

### PR DESCRIPTION
**Pull request by nvlsianpu**
Synch up to upstream https://github.com/mcu-tools/mcuboot/commit/05143ce2361829c4f05e036bdb9177676f9bb297

Fixed serial recovery skipping on nrf5340
Fixed issue which caused that progressive's erase feature was off although was selected by Kconfig (introduced by #42c985cead)
Added check of reset address in incoming image validation phase, see `CONFIG_MCUBOOT_VERIFY_IMG_ADDRESS`
Allow image header bigger than 1 KB for encrypted images
Fixed build with image encryption using RSA (issue introduced by migration to mbedTLS 3.0.0)
stm32: watchdog support
many documentation improvements

Merge using **Merge by Create a Merge commit!**

### CODE REVIEW

**Comment by utzig** [comment]
There's one extra commit which you could also include here.

**Review by utzig — APPROVED** [review]
LGTM

**Review by de-nordic — APPROVED** [review]
Looks OK

**Comment by utzig** [comment]
The failing CI jobs were added since last sync, so an Admin must disable them.

**Pull request merged**
