### PR TITLE
boot: zephyr: boards: add support for M5stack CoreS3/CoreS3SE

### PR DESCRIPTION
**Pull request by soburi**
Add m5stack_cores3/esp32s3/procpu and m5stack_cores3/esp32s3/procpu/se board targets.
Adds an overlay to disable devices that cause dependency conflicts.

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Comment by nordicjm** [comment]
Rebase needed for CI

**Review by nordicjm — CHANGES_REQUESTED** [review]
My bad, did not realise the repo, this needs to be submitted to https://github.com/mcu-tools/mcuboot

**Comment by soburi** [comment]
> My bad, did not realise the repo, this needs to be submitted to https://github.com/mcu-tools/mcuboot

Ah, I got it.

**Comment by nordicjm** [comment]
Merged in https://github.com/mcu-tools/mcuboot/pull/2159

**Pull request closed without merging**
