### PR TITLE
zephyr: remove Kconfig option CONFIG_USB

### PR DESCRIPTION
**Pull request by jfischer-no**
USB device support configuration is [revised](https://github.com/zephyrproject-rtos/zephyr/pull/36630) ,
CONFIG_USB option is deprecated.
Only USB_DEVICE_STACK option should be used to
enable USB device support.

### CODE REVIEW

**Comment by carlescufi** [comment]
Will you send this PR upstream as well?

**Review by carlescufi — APPROVED** [review]

**Comment by nvlsianpu** [comment]
@jfischer-no Can you send this patch to https://github.com/mcu-tools/mcuboot as well?
I'm ok with merging this here as well.

**Comment by jfischer-no** [comment]
> @jfischer-no Can you send this patch to https://github.com/mcu-tools/mcuboot as well?
> I'm ok with merging this here as well.

I can do it after it is merged here.

**Comment by nvlsianpu** [comment]
I see compilation error for nrf52dk_nrf52832 with this:
``` Console
-- Found devicetree overlay: /home/anpu/codedev/zephyrproject/bootloader/mcuboot/boot/zephyr/dts.overlay
Error: nrf52dk_nrf52832.dts.pre.tmp:559.1-13 Label or path zephyr_udc0 not found
FATAL ERROR: Syntax error parsing input tree
```

**Pull request merged**
