### PR TITLE
Synchronise with upstream (e512181)

### PR DESCRIPTION
**Pull request by henrikbrixandersen**
Synchronise up to mcu-tools/mcuboot@e512181 in order to pull in the fix in https://github.com/mcu-tools/mcuboot/pull/896

- allow xip-revert only for xip-mode
- boot: Fix LOAD_IMAGE_DATA macro
- bootutil: crypto: avoid unuseful memset
- ext: tinycrypt: update ctr mode to stream
- zephyr: use minimal CBPRINTF implementation
- zephyr/Kconfig: Added default pin for serial recovery mode for nRF5340DK
- boot: zephyr: Default to LOG_MINIMAL
- imgtool: Add support for setting fixed ROM address into image header
- boot: zephyr: cleanup NXP MPU configuration before boot
- fix nokogiri<=1.11.0.rc4 vulnerability
    
The remaining commits are related to MCUboot CI and tests.

Merge using **Merge by Create a Merge commit**!

### CODE REVIEW

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
Please add change list in the merge commit message.
https://github.com/zephyrproject-rtos/mcuboot/pull/39

**Comment by utzig** [comment]
I was discussing the workflow issues of signed-off-by commit checking with @nvlsianpu in pvt. The reason for the failure is because my committer email being used does not have a "signed-off-by" line, and it is using an email that I don't use for git at all. It is my primary email on GH (used for security reasons!). What I *think* happens is, when I use the option "Rebase and merge" if the PR is not at the tip of master, the rebase triggered by the UX uses my primary email on GH, so it ends up with this email which I don't really want to use. This is OK on upstream because the checks only run on PRs, not on master, but it fails when up merging. Since I don't want to use my nordicsemi email as my primary email on GH, a temporary solution for now is to be sure a PR is always up to date with master while I look for a better solution...

**Comment by nvlsianpu** [comment]
@utzig  Thanks for elaboration on this problem.

**Comment by henrikbrixandersen** [comment]
> Please add change list in the merge commit message.

Like this?

**Comment by nvlsianpu** [comment]
@henrikbrixandersen ^^ excellent

**Review by nvlsianpu — APPROVED** [review]

**Review by utzig — APPROVED** [review]

**Pull request merged**
