### PR TITLE
mcuboot supports the stm32 external octo-flash in XiP

### PR DESCRIPTION
**Pull request by FRASTM**
Prepare the boot/zephyr/flash_map_extended.c to support the stm32 MemoryMapped mode where the application is XiP from a external octo/quad flash memory
This is done by setting the CONFIG_STM32_MEMMAP flag which configures the octo/quad  flash stm32 driver in MemoryMapped mode
Then the application which is built/linked/stored in slot1_partition of the external ospi-nor-flash/qspi-nor-flash NOR flash is identified by the MCU boot, loaded and executed on the external NOR.

### CODE REVIEW

**Comment by FRASTM** [comment]
Requires the ../zephyr/drivers/flash/flash_stm32_ospi.c  to support the XiP as in https://github.com/zephyrproject-rtos/zephyr/pull/61082
$ west build  -p always -b b_u585i_iot02a  -d build_mcuboot ../bootloader/mcuboot/boot/zephyr
$ west flash -d build_mcuboot

**Comment by FRASTM** [comment]
when building the mcu boot there is no slot for image (no image only a mcuboot) flashing at boot_partition of the flash0

**Comment by nordicjm** [comment]
This is a mirror repository, it does not accept PRs. PRs must be posted upstream to https://github.com/mcu-tools/mcuboot

**Comment by FRASTM** [comment]
refer to https://github.com/mcu-tools/mcuboot/pull/1891

**Pull request closed without merging**
