### PR TITLE
[RFC][DNM] imgtool: Add support for setting fixed ROM address into image header

### PR DESCRIPTION
**Pull request by de-nordic**
The commit adds support for IMAGE_F_ROM_FIXED flag that allows setting
information on image base address into image_header.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

NOTE: This PR is here temporarily as a part of this draft: https://github.com/zephyrproject-rtos/zephyr/pull/29974

### CODE REVIEW

**Comment by nvlsianpu** [comment]
cc @davidvincze

**Review by nvlsianpu — COMMENTED** [review]
As I understand this will go to https://github.com/mcu-tools/mcuboot

Looks good to me.

**Comment by de-nordic** [comment]
> 
> 
> As I understand this will go to https://github.com/mcu-tools/mcuboot
> 
> Looks good to me.

Yes, I just wanted to pitch the idea to limited crowd as I am not even sure whether the repo is right: on my system imgtool has been installed via pip I think as it is not used from the mcuboot repo, so there might be another repo to keep the imgtool only.

**Comment by utzig** [comment]
> Yes, I just wanted to pitch the idea to limited crowd as I am not even sure whether the repo is right: on my system imgtool has been installed via pip I think as it is not used from the mcuboot repo, so there might be another repo to keep the imgtool only.

`imgtool` is published from https://github.com/mcu-tools/mcuboot every time the version is changed.

**Comment by de-nordic** [comment]
Moved here: https://github.com/mcu-tools/mcuboot/pull/898

**Pull request closed without merging**
