### PR TITLE
Upmerge up to upstream v1.6.0-rc2

### PR DESCRIPTION
**Pull request by nvlsianpu**
mergeup: merge up to upstream 82c5f7c
    
    Synchronize up to
    
    https://github.com/JuulLabs-OSS/mcuboot/commit/82c5f7
    which is same as v1.6.0-rc2 tag.
    
    Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

manifest upgrade https://github.com/zephyrproject-rtos/zephyr/pull/25071

### CODE REVIEW

**Comment by utzig** [comment]
@nvlsianpu Commits https://github.com/zephyrproject-rtos/mcuboot/pull/16/commits/39d1aef28cacde4de2ca3f65fa31ba18925e46ea, https://github.com/zephyrproject-rtos/mcuboot/pull/16/commits/48b8ef0a9231cd2d16ed4dcb479472c4d33ac708 and https://github.com/zephyrproject-rtos/mcuboot/pull/16/commits/5657d00e662adbd32addc8525862249b631334c5 are not upstreamed, should they be here?

**Comment by nvlsianpu** [comment]
@utzig This is the firs upmerge with real git-merge as @galak merged his PR here. Reverts commit helps to merge without conflict.

**Comment by nvlsianpu** [comment]
DNM - do not merge manually, will merge by push instead as want to have descriptive merge commit message..

**Comment by utzig** [comment]
> @utzig This is the firs upmerge with real git-merge as @galak merged his PR here. Reverts commit helps to merge without conflict.

Ah, I haven't seen they were merged, my bad. To track upstream correctly I think you would have to force push `master` with those two commits dropped, but I am not sure how good an idea that would be! :smile:

**Comment by nvlsianpu** [comment]
> To track upstream correctly I think you would have to force push master with those two commits dropped, but I am not sure how good an idea that would be! 😄

Would be the best solution IMO, not sure whether can be accepted by the others. I can make a snapshot-tag at current master here and make a force push. @carlescufi ?

**Pull request merged**
