### PR TITLE
mergeup: merge up to upstream 97e966a

### PR DESCRIPTION
**Pull request by nvlsianpu**
Downstream #b7254d1 has been reverted as it comes from the upsteram as well (it is clean merge thank to this)

Merge gives empty diff with the upsteram https://github.com/JuulLabs-OSS/mcuboot/commit/9b48d08dfc28742e4bd390ce6f981aa5e470df55

### CODE REVIEW

**Comment by nvlsianpu** [comment]
cc @de-nordic

**Comment by nvlsianpu** [comment]
DNM - do not merge manually, will merge by push instead as want to have descriptive merge commit message..

**Comment by de-nordic** [comment]
@nvlsianpu While testing this whit https://github.com/zephyrproject-rtos/zephyr/pull/26042/files#submit-review I have found that I have botched the update of CMakeLists.txt for mcuboot while posting the Single image. Would it be possible to include this: https://github.com/JuulLabs-OSS/mcuboot/pull/752 with this, to fix the problem with not compiling serial image recovery when single image is enabled?

**Comment by nvlsianpu** [comment]
@de-nordic Thanks for this finding. Of course yes.

**Comment by nvlsianpu** [comment]
@de-nordic Done

**Comment by pabigot** [comment]
+1 but I'm not a member so I can't review formally.  (Just tested it with the qspi patches, works fine).

**Comment by nvlsianpu** [comment]
@carlescufi ping

**Comment by carlescufi** [comment]
> Since Zephyr does not use our downstream NCS tooling related to reverts and reapplication of patches to track out of tree customizations, I think we should just update the revision in zephyr/west.yml to point to [97e966a](https://github.com/zephyrproject-rtos/mcuboot/commit/97e966a22623076fc72aa2cea2eb6597cf460837) instead, and use tags or branches to keep the old history around. @carlescufi ?

The thing is we have not standardized yet how to deal with these updates. I think what @nvlsianpu did here is safer, but I would like to see (in the case of this particular west project) a 0-diff between the HEAD of this  PR and a corresponding SHA of the upstream MCUboot.
I really want to avoid force-pushing into these repositories before we've decided on a standard way on dealing with this at a zephyr-wide level, @mbolivar-nordic. This is currently being discussed in the process meetings.

**Pull request merged**
