### PR TITLE
[DNM] Upmerge 6 10 2020

### PR DESCRIPTION
**Pull request by nvlsianpu**
Improvements:
- hardening against hardware level fault injection and timing attacks
- Abstract crypto primitives to simplify porting.
- boot: Add ram-load upgrade mode
- renamed single-image mode to single-slot mode

- kconfig: provide logic for setting key file, simplify prj.conf

- imgtool: Print image digest during verify
- imgtool: Add possibility to set confirm flag for hex files as well
- imgtool: --confirm implies --pad

- Added single-slot Zephyr-RTOS test build

fixes:
- bootutil: fix boostrapping in swap-move
- Disable HW stack protection (temporary hack)
- reset SPLIM registers before boot
- fixes build issue that occurs if CONF_FILE contains multiple file paths instead of single file path.
- imgtool: Fix 'custom_tlvs' argument handling
- Turn off cache for Cortex M7 before chain-loading.- hardening against hardware level fault injection and timing attacks

Conflict resolved in boot/zephyr/sample.yaml file

### CODE REVIEW

**Review by utzig — COMMENTED** [review]
I think we better wait while I work on https://github.com/JuulLabs-OSS/mcuboot/pull/830, it might be an important bug to also have a fix for so can be added here as well, I'll let you know soon.

**Review by utzig — APPROVED** [review]
LGTM

**Comment by utzig** [comment]
@nvlsianpu Feel free to disregard my previous comment, I can submit a new upmerge once the current wip bug fixing is done.

**Comment by utzig** [comment]
You should also add https://github.com/JuulLabs-OSS/mcuboot/pull/830 once it's merged!

**Comment by nvlsianpu** [comment]
encountered https://github.com/JuulLabs-OSS/mcuboot/pull/831
need to include patch: https://github.com/JuulLabs-OSS/mcuboot/pull/832

**Review by de-nordic — APPROVED** [review]
Looks OK.

**Comment by mniestroj** [comment]
Is `check how sanitychec process tests` added by mistake?

**Comment by utzig** [comment]
@nvlsianpu https://github.com/zephyrproject-rtos/mcuboot/pull/36/commits/f3108df869a511f7f6ac0f4ccf84add44a14e5c0 is only for testing, correct?

**Comment by nvlsianpu** [comment]
> @nvlsianpu f3108df is only for testing, correct?

Yes it was. I dropped it.  @utzig, @de-nordic @mniestroj  Please revisit

**Review by mniestroj — APPROVED** [review]

**Review by utzig — APPROVED** [review]
LGTM

**Comment by nvlsianpu** [comment]
cc @carlescufi Can I merge this update? It fixes few issue we have.

**Review by de-nordic — APPROVED** [review]
Looks OK.

**Pull request merged**
