### PR TITLE
synchronized up to https://github.com/mcu-tools/mcuboot/commit/9b97456eb2e24e75932c63e6d237bd1b94fffc7a

### PR DESCRIPTION
**Pull request by nvlsianpu**
Synch up to:
https://github.com/mcu-tools/mcuboot/commit/9b97456eb2

* boot_serial: allow to build when CONFIG_MULTITHREADING=n
* allow to not provide scratch area definition if scratch algorithm is not used.

Signed-off-by: Andrzej Puzdrowski andrzej.puzdrowski@nordicsemi.no

Merge using **Merge by Create a Merge commit!**

### CODE REVIEW

**Comment by utzig** [comment]
@nvlsianpu You should also create a `main` branch here since MCUboot switched to it.

**Review by utzig — APPROVED** [review]
LGTM

**Review by de-nordic — APPROVED** [review]
Looks OK.

**Review by de-nordic — APPROVED** [review]
Looks OK. Thanks!

**Pull request merged**
