### PR TITLE
[DNM] synchronize up to 5a6e181 upsteram

### PR DESCRIPTION
**Pull request by nvlsianpu**
synchronize up to https://github.com/zephyrproject-rtos/mcuboot/commit/a468fce1ed326205518bf0f7922339010cf1c652

Upmerge solves https://github.com/advisories/GHSA-mqm2-cgpr-p4m6 issue

This patch shows how looks like pure UI mergeable synchronizatin PR.

### CODE REVIEW

**Comment by nvlsianpu** [comment]
manifest PR: https://github.com/zephyrproject-rtos/zephyr/pull/27494

**Comment by utzig** [comment]
This is OK but you could also bring in the XIP commits now!

**Comment by utzig** [comment]
Btw, this only affects publishing of the docs through Jekyll, which is what ends up on mcuboot.com. For NCS those markdown files are parsed by recommonmark and the issue won't exist for that case, and Zephyr does not publish the docs I suppose.

**Comment by nvlsianpu** [comment]
@utzig ok, I did it.

**Pull request merged**
