### PR TITLE
End of history notification

### PR DESCRIPTION
**Pull request by de-nordic**
This is final commit in this history line for MCUboot fork, zephyrproject-rtos/zephyr. The commit will be only accessible on branch zephry-v3.3.0-final.

The issue has been described in details here:
https://github.com/zephyrproject-rtos/zephyr/issues/55303

Briefly: while doing some synchronizations we have brought commits that we did not want in Zephyr fork andlater synchronization has duplicated some commits in history; the commits we did not wanted have been reverted upstream anyway and bringing reverts of something we have reverted is again problematic.

That is why we have device to reset the history by overwriting main branch of zephyrproject-rtos/mcuboot with mcutools/mcuboot main branch with 59624334748129cb93f096408911a227b0dd64c0 top commit.

### CODE REVIEW

**Comment by carlescufi** [comment]
>branch zephry-v3.3.0-final

Did we decide to branch and not to tag? Can we do both?

**Review by nordicjm — APPROVED** [review]

**Comment by de-nordic** [comment]
> > branch zephry-v3.3.0-final
> 
> Did we decide to branch and not to tag? Can we do both?

@carlescufi I can do both. Message same as in commit? Name of the tag?

**Comment by carlescufi** [comment]
> > > branch zephry-v3.3.0-final
> > 
> > 
> > Did we decide to branch and not to tag? Can we do both?
> 
> @carlescufi I can do both. Message same as in commit? Name of the tag?

Yes, and name of the tag can be the same of the branch. But I'd like to propose a new name for the branch and tag:
`zephyr-v3.3.0-snapshot`. This is a better way of communicating that we are "snapshotting" the history for preservation.

**Comment by de-nordic** [comment]
> 
> Yes, and name of the tag can be the same of the branch. But I'd like to propose a new name for the branch and tag: `zephyr-v3.3.0-snapshot`. This is a better way of communicating that we are "snapshotting" the history for preservation.

Changing as suggested.

**Comment by de-nordic** [comment]
@carlescufi Below is tag message, it differs a little bit from commit message, as this is tag message
```
End of history notification

This is final tag in this history line for MCUboot fork,
zephyrproject-rtos/zephyr. The tagged commit, and the old history
will be accessible via this tag and on branch zephyr-v3.3.0-snapshot.

The issue has been described in details here:
https://github.com/zephyrproject-rtos/zephyr/issues/55303

Briefly: while doing some synchronizations we have brought
commits that we did not want in Zephyr fork andlater synchronization
has duplicated some commits in history; the commits we did not wanted
have been reverted upstream anyway and bringing reverts of something
we have reverted is again problematic.

That is why we have device to reset the history by overwriting
main branch of zephyrproject-rtos/mcuboot with mcutools/mcuboot
main branch with 59624334748129cb93f096408911a227b0dd64c0 top
commit.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>
```
I can not push it till the branch gets merged (can I?) because the referenced commit does not exist yet on main.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
