### PR TITLE
zephyr: require CRC to be enabled

### PR DESCRIPTION
**Pull request by nashif**
CRC routines were originally built unconditionally, now we need to
enable CONFIG_CRC to make them available.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

### CODE REVIEW

**Review by str4t0m — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by nvlsianpu — CHANGES_REQUESTED** [review]
patch should go to the mcu-tool/mcuboot firs

**Comment by nvlsianpu** [comment]
@nashif Can this be added using `imply` in Kconfig, Somwhere there: https://github.com/zephyrproject-rtos/mcuboot/blob/main/boot/zephyr/Kconfig#L12?

Bidirectorial synchronization are nightmare, that why I'm insisting.

**Comment by nashif** [comment]
> Bidirectorial synchronization are nightmare, that why I'm insisting.

we have this as a module here for this case exactly, I am not sure how else this would work. if mcuboot can take a Kconfig that does not exist and not complain about it, that should work.

**Comment by stephanosio** [comment]
> Can this be added using `imply` in Kconfig

Is it the mcuboot (or the Zephyr port for it) itself that requires CRC? or the mcuboot **sample**? If the former, then `MCUBOOT` should `select CRC`.

**Comment by stephanosio** [comment]
> that patch will not work with upstream mcuboot, i.e. it can't be merged until zephyr has moved to use the new kconfig.

I suppose overriding the CI (merging in spite of failures) on the mcuboot side is an option?

**Comment by nvlsianpu** [comment]
@nashif 
Better patch would be `select CRC` under https://github.com/zephyrproject-rtos/mcuboot/blob/main/boot/zephyr/Kconfig.serial_recovery#L8.

Please send the same patch to the mcu-tools/mcuboot.

**Comment by tejlmand** [comment]
@nashif @nvlsianpu please see a proposal here: https://github.com/zephyrproject-rtos/zephyr/pull/50670#discussion_r1027990995

then after #50670 has been merged and CRC is available in the tree then MCUboot prj.conf can start using CONFIG_CRC=y` and we can consider removing the default in future.

**Comment by de-nordic** [comment]
Already merged upstream, closing.

**Pull request closed without merging**
