### PR TITLE
synchronization 16122012

### PR DESCRIPTION
**Pull request by nvlsianpu**
Synch up to upstream https://github.com/mcu-tools/mcuboot/commit/1eedec3e7936f74872aca43f3962246e7abe6439

- fixed the build issue caused by removal of CONFIG_SYSTEM_CLOCK_DISABLE property (within https://github.com/zephyrproject-rtos/zephyr/pull/37435)
- always call sys_clock_disable() in main since the empty sys_clock_disable() callback is provided if the platform doesn't support system clock disable capability.
- bootutil: Close flash_area after failure to read swap status information
- fixed status offset calculation in case of scratch area
- fixed include path for reboot.h header.

Merge using **Merge by Create a Merge commit!**

### CODE REVIEW

**Review by utzig — APPROVED** [review]
LGTM

**Comment by utzig** [comment]
@nvlsianpu Probably better to wait for 1217 merge and get latest version!

**Review by de-nordic — APPROVED** [review]

**Comment by utzig** [comment]
The message above needs to be updated to point to the new commit HEAD you added after this PR was opened.

**Comment by utzig** [comment]
> @nvlsianpu Probably better to wait for 1217 merge and get latest version!

I would skip this one, too risky and not needed right now, better to do a new sync in a week than having to revert stuff!

**Comment by nvlsianpu** [comment]
>> @nvlsianpu Probably better to wait for 1217 merge and get latest version!

>I would skip this one, too risky and not needed right now, better to do a new sync in a week than having to revert stuff!

I will stick to current upgrade range.

**Pull request merged**
