### PR TITLE
Zephyr to mcuboot 1.8

### PR DESCRIPTION
**Pull request by d3zd3z**
Move mcuboot up to the latest, right before the expected 1.8.0-rc1.

### CODE REVIEW

**Comment by nvlsianpu** [comment]
@d3zd3z I see conflict here here.

**Comment by sylvioalves** [comment]
@nvlsianpu @d3zd3z When do you expect to get this merged?

**Comment by nvlsianpu** [comment]
@sylvioalves This depends one mbed TLS upgrade and RFM upgrade. So after the 2.7.0 release for sure.

**Comment by d3zd3z** [comment]
This change shouldn't depend on the newer Mbed TLS. I'm not sure what the issues are with TF-M compatibility. I can see advantages to getting the newer version into the Zephyr LTS, but it is also fairly late to do so.

**Comment by d3zd3z** [comment]
@nvlsianpu Should we do this "properly" now to get 1.8.0 into Zephyr fully, as part of the mbed TLS upgrade. You'd mentioned basically backing out the other effort, and setting upstream to this. If we set the head to this, I suspect it'll look like a lot of commits will be redundant. Should this be a new branch, with just the local changes cherry-picked over?

**Comment by carlescufi** [comment]
> @nvlsianpu Should we do this "properly" now to get 1.8.0 into Zephyr fully, as part of the mbed TLS upgrade. You'd mentioned basically backing out the other effort, and setting upstream to this. If we set the head to this, I suspect it'll look like a lot of commits will be redundant. Should this be a new branch, with just the local changes cherry-picked over?

@d3zd3z, @nvlsianpu is currently away and will not be back for the next couple of weeks. I suggest @de-nordic take a look and you both agree together how to move on with this.

**Comment by nvlsianpu** [comment]
> @nvlsianpu Should we do this "properly" now to get 1.8.0 into Zephyr fully, as part of the mbed TLS upgrade. You'd mentioned basically backing out the other effort, and setting upstream to this. If we set the head to this, I suspect it'll look like a lot of commits will be redundant. Should this be a new branch, with just the local changes cherry-picked over?

This should be synchronization using merge. This really help to track changes using git history and makes a commit skip very unlikely.

Would be great to ensure empty-diff with the upstream version to which it will be synchronized.

**Comment by d3zd3z** [comment]
I've pushed a merge commit, and verified that this tree exactly matches the upstream v1.8.0-rc2.

**Review by SebastianBoe — APPROVED** [review]

**Review by nvlsianpu — COMMENTED** [review]
where is this commit https://github.com/mcu-tools/mcuboot/commit/d96d617018cd531a677140bc7bc744136d87a4d8- it is parrent of Preps for 1.8.0-rc2 commit

**Review by nvlsianpu — APPROVED** [review]
^^ looks like I mad early finding basing on how GH presents git history.
Pr Is fine.

**Comment by carlescufi** [comment]
@nvlsianpu should I merge this with the "Merge pull request" option directly from the web GUI?

**Pull request merged**
